language: php

before_script:
- composer self-update 1.10.15
- composer install --prefer-source
- "./test/prism.sh &"
- sleep 20
- cd test

script:
- "../vendor/bin/phpunit . --filter test*"

after_script:
- cd ../
after_success:
- bash <(curl -s https://codecov.io/bash)

php:
- 5.6
- 7.0
- 7.1
- 7.2
